In [169]:
import pandas as pd
import os
import tabula

# Define os caminhos
base_path = os.path.join(os.getcwd(), 'docs', 'Source', 'B15', 'DDR')

# Lista todos os arquivos PDF no diretório especificado
pdf_files = [f for f in os.listdir(base_path) if f.lower().endswith('.pdf')]

# Páginas a serem extraídas (lista vazia para extrair todas as páginas)
pages_to_extract = []

specified_dfs = []

for pdf_file in pdf_files:
    pdf_path = os.path.join(base_path, pdf_file)
    try:
        dfs_list = []
        if pages_to_extract:
            for page_num in pages_to_extract:
                # Lê a página especificada do arquivo PDF
                dfs = tabula.read_pdf(pdf_path, pages=page_num,
                                      relative_area=True,
                                      relative_columns=True)
                if dfs:
                    dfs_list.extend(dfs)  # Adiciona os DataFrames da página especificada à lista
                    print(f"Successfully read {len(dfs)} tables from page {page_num} of {pdf_file}")
                else:
                    print(f"No tables found in page {page_num} of {pdf_file}")
        else:
            # Lê todas as páginas do arquivo PDF
            dfs = tabula.read_pdf(pdf_path, pages='all',
                                  relative_area=True,
                                  relative_columns=True)
            if dfs:
                dfs_list.extend(dfs)  # Adiciona todos os DataFrames do arquivo à lista
                print(f"Successfully read all tables from {pdf_file}")
            else:
                print(f"No tables found in {pdf_file}")
        
        specified_dfs.append((pdf_file, dfs_list))
    except Exception as e:
        print(f"Error reading {pdf_file}: {e}")

print(f"Total number of PDF files processed: {len(specified_dfs)}")

Jun 20, 2024 4:44:36 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Helvetica
Jun 20, 2024 4:44:36 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Helvetica

Successfully read all tables from BAV-102- WO DDR-01-July-18.pdf

Jun 20, 2024 4:44:37 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Helvetica
Jun 20, 2024 4:44:37 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for Helvetica

Successfully read all tables from BAV-102- WO DDR-01-July-17.pdf
Total number of PDF files processed: 2

In [170]:
# Display all DataFrames from each specified page of each PDF file
for pdf_file, dfs_list in specified_dfs:
    print(f"\nTables from {pdf_file}:\n")
    for idx, df in enumerate(dfs_list):
        print(f"Table {idx + 1} from {pdf_file}:\n")
        display(df)  # Use display() if in Jupyter Notebook, otherwise use print(df)

Tables from BAV-102- WO DDR-01-July-18.pdf:

Table 1 from BAV-102- WO DDR-01-July-18.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,Curr. KB to Mud,Time Log Hrs,NaN,Target Depth,Target Depth,Depth End (MD),End Depth,Duration
2,(days) (days),Water Depth (ft),(ft),Current RKB,Line (ft),(hr),Drill Hrs (hr),(MD) (ftKB),(TVD) (ftOTH),(ftKB),(TVD) (ftOTH),(days)
3,1 1 54,"1,281.00",202.00,"202.00,","1,483.00",24.00,NaN,"11,205","14,906.5","11,455",NaN,115.16
4,Daily Operations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
61,Drill Gas Summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Avg Background Gas Max Background Gas,NaN,Avg Connection Gas,Max Connection Gas,Avg Trip Gas,NaN,Max Trip Gas,Avg Drill Gas,NaN,Max Drill Gas,Max H2S (ppm),NaN
63,0.00 0.00,NaN,0.00,0.00,0.00,NaN,0.00,0.00,NaN,0.00,0,NaN
64,Mud Checks (WSEA 4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Time Mud/Brine Type,Fluid Density (lb/gal) PV Calc (cP),NaN,YP Calc (lbf/100ft2),Low Gravity Solids (PNroApFo/rWtioante) r Ratio,NaN,Electric Stability (V),"Water Phase Salinity H(mTgH/PL )FC (1/32"")",NaN,Low Shear Rate YieldV Piso 6inrtp (mlbf/100ft2),NaN,NaN

Table 2 from BAV-102- WO DDR-01-July-18.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,1200313412,"73,336,000","103,571,861 91,083,426","362,306 24.00",NaN,"5,096,832",No
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARRO,2023,TESTE,Environmental,TESTE,TESTE,TESTE

Table 3 from BAV-102- WO DDR-01-July-18.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,NaN,Original RKB,NaN,Curr. KB to Mud Time Log Hrs,NaN,Target Depth,Target Depth,Depth End (MD),End Depth,NaN,Duration
2,(days) (days),NaN,Water Depth (ft),(ft),Current RKB,Line (ft) (hr),Drill Hrs (hr),(MD) (ftKB),(TVD) (ftOTH),(ftKB),(TVD) (ftOTH),NaN,(days)
3,1 1,NaN,"1,281.00",202.00,"202.00,","1,483.00 24.00",NaN,"22,205","15,906.5","17,455",NaN,NaN,115.16
4,Job Time Log,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Start Cum Dur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unsch,NaN
6,Time Dur (hr) (hr),NaN,Hole/Csg Size,Well Phase,Phase,Activity,NaN,Com,NaN,NaN,NaN,Time (hr),Ref No.
7,"00:00 10.00 3,596",NaN,8 1/2 D,NaN,PRO,Continued,NaN,NaN,NaN,NaN,NaN,10.00,48
8,.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"10:00 0.25 3,596",NaN,8 1/2 D,NaN,PRO,Held,NaN,NaN,NaN,NaN,NaN,0.25,48
10,.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"10:15 0.50 3,596",NaN,8 1/2 D,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,0.50,48
12,.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"10:45 1.25 3,598",NaN,8 1/2 D,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,1.25,48
14,.00,NaN,NaN,NaN,NaN,filled & break circulation every 20 stands.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,"- 12,492' MD: 250 gpm, 1,797 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.5+ ppg / 10.5+ ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"12:00 0.25 3,598",NaN,8 1/2 D,NaN,PRO,Held,NaN,NaN,NaN,NaN,NaN,0.25,48
19,.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"12:15 2.00 3,600",NaN,8 1/2 D,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,2.00,48
21,.25,NaN,NaN,NaN,NaN,filled & break circulation every 20 stands.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,"- 12,492' MD: 250 gpm, 1,797 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,"- 14,290' MD, 250 gpm, 1,861 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.5+ ppg / 9.6+ - 10.5+ ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"14:15 1.50 3,601",NaN,8 1/2 DR,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,1.50,48
27,.75,NaN,NaN,NaN,NaN,filled & break circulation.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,"- 15,239' MD: 250 gpm, 1,992 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.5 ppg / 9.7 ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,"- Confirmed MWD tool temp at 15,239' MD ( 287 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,"to (TOL 16,000' MD 300 F).",NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,"Decision made to wash down from 16,000' MD to ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,temperature on MWD tools.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"15:45 0.25 3,602",NaN,8 1/2 G,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,0.25,48
37,.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"16:00 0.25 3,602",NaN,8 1/2 LG,NaN,PRO,Held Well,NaN,NaN,NaN,NaN,NaN,0.25,48
39,.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,"16:15 1.25 3,603",NaN,8 1/2 LG,NaN,PRO,M/U,NaN,NaN,NaN,NaN,NaN,1.25,48
41,.50,NaN,NaN,NaN,NaN,"16,365' MD, 250 gpm, 2,181 psi - 2,550 psi.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,Parameters.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,"- 16,370' MD, S/O: 298 k , 30 rpm, 8 k trq. (P...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,"- 16,370' MD, P/U: 352 k, S/O 305 k (Pumps Off)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.4 - 10.5 ppg / 9.7 - 10+ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,- MWD tool D/H Temp: 290 F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 4 from BAV-102- WO DDR-01-July-18.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,NaN,NaN,NaN,24.00,NaN,"5,096,832",No
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARR0,2023,TESTE,TESTE,TESTE,TESTE,TESTE

Table 5 from BAV-102- WO DDR-01-July-18.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,Curr. KB to Mud Time Log Hrs,NaN,NaN,Target Depth,Target Depth,Depth End (MD),End Depth,NaN,Duration
2,(days) (days),Water Depth (ft),(ft) Current RKB,NaN,Line (ft) (hr),Drill Hrs (hr),NaN,(MD) (ftKB),(TVD) (ftOTH),(ftKB),(TVD) (ftOTH),NaN,(days)
3,54 54,"1,281.00","202.00 202.00,",NaN,"1,483.00 24.00",NaN,NaN,"22,205","15,906.5","17,455",NaN,NaN,115.16
4,Job Time Log,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Start Cum Dur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unsch,NaN
6,Time Dur (hr) (hr),Hole/Csg Size,Well Phase,Phase,Activity,NaN,NaN,Com,NaN,NaN,NaN,Time (hr),Ref No.
7,"17:30 2.50 3,606",8 1/2 DR,PRO,NaN,Continued to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,.00,NaN,NaN,NaN,"250 gpm, 2500 psi. Commenced wash & ream from...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,"MD, 20 rpm, 7 k trq.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,- Run through TOL - slick. MW in/out: 10.4 - 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,"- TG: 2% while entering 7"" Liner. SPP graduall...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,"from 15,000' MD.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"20:00 3.50 3,609",8 1/2 LG,PRO,NaN,Circulated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,.50,NaN,NaN,NaN,"Pump rate: 350 gpm / SPP: 3,800 - 3,520 psi.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,TDS rotary: 20 -30 rpm / TRQ: 9-10 k.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,"Gas: 2.42 %. MW in/out: 10.5, 10.5+ / 10.6+, 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,Initial ECD: 12 ppg and Final ECD: 10.98 ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,"- Performed Table top choke drill with TP, Dri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,RSP and POA with Data and Mud engineers.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,- Observed discrepancy between Geolog and NOV'...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,psi difference).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,- Bottom Up at surface MW in/out: 10.5+ and 10...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,"- After 1.5 BU MW in: 10.5, 10.4+ / MW out: 10...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"23:30 0.50 3,610",8 1/2 G,PRO,NaN,Commenced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,.00,NaN,NaN,NaN,T Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,"FR: 300 gpm / SPP: 2,901 psi.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,WOB: 5-8 / TRQ: 11-12 Rotation: 80 rpm.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,MW in: 10.5 ppg & MW out: 10.5 ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,- Recorded PUW: 362 k / SOW; 308 k / ROW: 340 k.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,"- After BPUTS at 17,314' MD, observed SPP from...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Offline Activity Time Logs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Start Date,Dur (hr),Activity,NaN,Inactive?,NaN,NaN,NaN,Com,NaN,NaN,NaN,NaN
36,Unscheduled Events,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Ref No. Unscheduled EvSetnatr tT Dypaete,NaN,Dur (Net) (hr),Unscheduled Major Category,Unscheduled Detail,NaN,NaN,Start Depth (MD) (ftOTH) End Depth (MD) (ftOTH),NaN,Estimated Cost (Cost),NaN,NaN,Exclude from NPT Calculation
38,48 NPT 5/16/2024 07:15,NaN,106.25,RREQ,TOP DRIVE,NaN,NaN,"16,300","16,300",NaN,NaN,NaN,N
39,Event Description,NaN,NaN,NaN,NaN,NaN,Accountable Party,NaN,NaN,Service Contractor,NaN,NaN,NaN
40,Continue waiting,NaN,NaN,NaN,NaN,NaN,Rig Contractor,NaN,NaN,TTTT,NaN,NaN,NaN
41,Job Supplies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Job Supply Type,Supply Item Des,NaN,Received,Returned,NaN,NaN,Consumed,Cum On Loc,NaN,Cum Consumed,NaN,NaN
43,Water,Non-potable Water,NaN,NaN,0.0,0.0,NaN,11.0,NaN,"4,168.0",NaN,NaN,"19,497.0"
44,Water,Potable Water,NaN,NaN,298.0,0.0,NaN,255.0,NaN,"6,277.0",NaN,NaN,"33,016.0"
45,Base Fluid,Non-aqueous,NaN,NaN,0.0,0.0,NaN,8.0,NaN,"1,070.0",NaN,NaN,"1,978.0"
46,Base Fluid,Diesel,NaN,NaN,0.0,0.0,NaN,71.0,NaN,"3,350.0",NaN,NaN,"13,713.0"
47,Cement,Class G,NaN,NaN,0.0,0.0,NaN,0.0,NaN,"-4,947.0",NaN,NaN,"9,894.0"
48,Cement,Blend,NaN,NaN,0.0,0.0,NaN,0.0,NaN,"3,556.0",NaN,NaN,"3,319.0"
49,Brine,KCl,NaN,NaN,0.0,0.0,NaN,0.0,NaN,"1,280.0",NaN,NaN,457.0
50,Cement,Neat,NaN,NaN,0.0,0.0,NaN,0.0,NaN,-825.0,NaN,NaN,"2,959.0"
51,"Drill String/BHA: BHA #<StringNo>, <Des>",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,String Components,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IADC Bit Dull Out,NaN,NaN,NaN
53,Size (in) Model,Serial Number,Depth In (ftOTH),NaN,Depth Out (ftOTH) Total Depth Drilled by Bit (...,NaN,NaN,Total Avg ROP (ft/hr),NaN,String Length (ft),String Wt (1000lbf),NaN,NaN
54,Drill String Drilling Parameter: <DepthStart> ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Start Depth (TVD) (ftOTH),End Depth (TVD) (ftOTH),Depth Start (MD) (ftOTH),NaN,Depth End (MD) (ftOTH),Interval Depth Drilled (ft),NaN,NaN,Drill Time w/connections (hr),NaN,Interval ROP (ft/hr),NaN,NaN
56,RPM (rpm) Motor RPM (rpm),NaN,Weight on Bit (1000lbf),NaN,PU Str Wt (1000lbf) SO Str Wt (1000lbf),NaN,NaN,Drilling Torque,Off Bottom Torque,NaN,ROP Instantaneous (ft/hr),NaN,NaN
57,Hydraulic Calculations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Mud Density (lb/gal) TFA (incl Noz) (in2),Flow Rate (gpm),SPP (psi),NaN,Bit Jet Velocity (ft/s) Bit Pressure Drop (psi),NaN,HSI (hp/in2),ECD End (lb/gal),NaN,Min Open Hole AV (ft/min),Max Open Hole AV (ft/min),NaN,NaN
59,Error,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 6 from BAV-102- WO DDR-01-July-18.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,NaN,NaN,NaN,24.00,NaN,"5,096,832",NaN
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARRO,2023,TESTE,TESTE,TESTE,TESTE,TESTE

Table 7 from BAV-102- WO DDR-01-July-18.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,Curr. KB to Mud Time Log Hrs,NaN,Target Depth,Target Depth,Depth End (MD) End Depth,NaN,NaN,Duration
2,(days) (days),Water Depth (ft),(ft),Current RKB,Line (ft) (hr) Drill Hrs (hr),NaN,(MD) (ftKB),(TVD) (ftOTH),(ftKB) (TVD) (ftOTH),NaN,NaN,(days)
3,54 54,"1,281.00","202.00 202.00,",NaN,"1,483.00 24.00",NaN,"22,205","15,906.5","17,455",NaN,NaN,115.16
4,Casing Strings (WSEA 5),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
73,AFE Number Total AFE Amount (Cost),NaN,Total AFE + Sup Amount (Cost)Cum Field Est To ...,NaN,Daily Field Est Total (Cost),NaN,Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?,NaN,NaN,NaN
74,"73,336,000",NaN,NaN,NaN,NaN,24.00,NaN,NaN,NaN,NaN,NaN,NaN
75,Well Name Wellbore,NaN,Job Category,NaN,Job Complexity Complex Job Assessment,NaN,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor,NaN,NaN,NaN
76,2023,NaN,TESTE,NaN,TESTE,NaN,TESTE,TESTE,TESTE,NaN,NaN,NaN
77,CARRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 8 from BAV-102- WO DDR-01-July-18.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,NaN,Curr. KB to Mud Time Log Hrs,NaN,NaN,Target Depth Target Depth,Depth End (MD),NaN,End Depth,Duration
2,(days) (days),Water Depth (ft),(ft),Current RKB,NaN,Line (ft) (hr),Drill Hrs (hr),NaN,(MD) (ftKB) (TVD) (ftOTH),(ftKB),NaN,(TVD) (ftOTH),(days)
3,54 54,"1,281.00",202.00,"202.00,",NaN,"1,483.00 24.00",NaN,NaN,"22,205","15,906.5 17,455",NaN,NaN,115.16
4,Last 5 Surveys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,DLS Build,Turn,NaN,NaN,NaN,NaN,Use for,Definitiv
6,Date,TVD (ftOTH),MD (ftOTH),Incl (°),NaN,Azm (°) (°/100ft) (°/100ft),(°/100ft),NaN,VS (ft),NS (ft) EW (ft),NaN,Prop/Actual Calcs?,e?
7,Geologic Horizons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
9,Miocene,NaN,NaN,NaN,NaN,"3,616",NaN,NaN,NaN,NaN,NaN,"3,620",NaN
10,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
11,CN10,NaN,NaN,NaN,NaN,"4,520",NaN,NaN,NaN,NaN,NaN,"4,521",NaN
12,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
13,CN9,NaN,NaN,NaN,NaN,"4,826",NaN,NaN,NaN,NaN,NaN,"4,827",NaN
14,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
15,CN8,NaN,NaN,NaN,NaN,"5,935",NaN,NaN,NaN,NaN,NaN,"5,938",NaN
16,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
17,CN6,NaN,NaN,NaN,NaN,"6,479",NaN,NaN,NaN,NaN,NaN,"6,474",NaN
18,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
19,CN3,NaN,NaN,NaN,NaN,"11,568",NaN,NaN,NaN,NaN,NaN,"11,505",NaN
20,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
21,PTS 0,NaN,NaN,NaN,NaN,"17,709",NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
23,PTS 5,NaN,NaN,NaN,NaN,"20,085",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Tubing Strings (run/pulled this Job),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,String Max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Nominal OD,NaN,Top Depth,NaN,Set Depth,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Run Date Pull Date,(in),Drift Min (in),(MD) (ftOTH),NaN,(MD) (ftOTH) Top Thread Wt (lb/ft),NaN,Grade,Des,NaN,NaN,Com,NaN
28,Other Strings/BHA: (still in hole),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,String Max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Nominal OD,NaN,Top Depth,NaN,Set Depth,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Run Date Pull Date,(in),Drift Min (in),(MD) (ftOTH),NaN,(ftOTH) Top Thread Wt (lb/ft),NaN,Grade,Tubing String,NaN,NaN,Com,NaN
32,Other in Hole (still in hole),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Run Date Pull Date,Fish Neck OD (in),NaN,Drift (in),NaN,Top (ftOTH) String,NaN,Des,NaN,Com,NaN,NaN,NaN
34,Perforations (this Job),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,Dens Fluis,P Over/Under Shot Dens Gun Left,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Date,Top (ftOTH),Btm (ftOTH),NaN,(lb/gal),(psi) (shots/ft) In Hole?,NaN,NaN,NaN,Com,NaN,NaN,NaN

Table 9 from BAV-102- WO DDR-01-July-18.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,NaN,"73,336,000","103,571,861 91,083,426","362,306 24.00",NaN,"5,096,832",No
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARRO,2023,TESTE,TESTE,TESTE,TESTE,TESTE

Tables from BAV-102- WO DDR-01-July-17.pdf:

Table 1 from BAV-102- WO DDR-01-July-17.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,Curr. KB to Mud,Time Log Hrs,NaN,Target Depth,Target Depth,Depth End (MD),End Depth,Duration
2,(days) (days),Water Depth (ft),(ft),Current RKB,Line (ft),(hr),Drill Hrs (hr),(MD) (ftKB),(TVD) (ftOTH),(ftKB),(TVD) (ftOTH),(days)
3,1 1 54,"1,281.00",202.00,"202.00,","1,483.00",24.00,NaN,"11,205","14,906.5","11,455",NaN,115.16
4,Daily Operations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
61,Drill Gas Summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Avg Background Gas Max Background Gas,NaN,Avg Connection Gas,Max Connection Gas,Avg Trip Gas,NaN,Max Trip Gas,Avg Drill Gas,NaN,Max Drill Gas,Max H2S (ppm),NaN
63,0.00 0.00,NaN,0.00,0.00,0.00,NaN,0.00,0.00,NaN,0.00,0,NaN
64,Mud Checks (WSEA 4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Time Mud/Brine Type,Fluid Density (lb/gal) PV Calc (cP),NaN,YP Calc (lbf/100ft2),Low Gravity Solids (PNroApFo/rWtioante) r Ratio,NaN,Electric Stability (V),"Water Phase Salinity H(mTgH/PL )FC (1/32"")",NaN,Low Shear Rate YieldV Piso 6inrtp (mlbf/100ft2),NaN,NaN

Table 2 from BAV-102- WO DDR-01-July-17.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,1200313412,"73,336,000","103,571,861 91,083,426","362,306 24.00",NaN,"5,096,832",No
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARRO,2023,TESTE,Environmental,TESTE,TESTE,TESTE

Table 3 from BAV-102- WO DDR-01-July-17.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,NaN,Original RKB,NaN,Curr. KB to Mud Time Log Hrs,NaN,Target Depth,Target Depth,Depth End (MD),End Depth,NaN,Duration
2,(days) (days),NaN,Water Depth (ft),(ft),Current RKB,Line (ft) (hr),Drill Hrs (hr),(MD) (ftKB),(TVD) (ftOTH),(ftKB),(TVD) (ftOTH),NaN,(days)
3,1 1,NaN,"1,281.00",202.00,"202.00,","1,483.00 24.00",NaN,"22,205","15,906.5","17,455",NaN,NaN,115.16
4,Job Time Log,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Start Cum Dur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unsch,NaN
6,Time Dur (hr) (hr),NaN,Hole/Csg Size,Well Phase,Phase,Activity,NaN,Com,NaN,NaN,NaN,Time (hr),Ref No.
7,"00:00 10.00 3,596",NaN,8 1/2 D,NaN,PRO,Continued,NaN,NaN,NaN,NaN,NaN,10.00,48
8,.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"10:00 0.25 3,596",NaN,8 1/2 D,NaN,PRO,Held,NaN,NaN,NaN,NaN,NaN,0.25,48
10,.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"10:15 0.50 3,596",NaN,8 1/2 D,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,0.50,48
12,.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"10:45 1.25 3,598",NaN,8 1/2 D,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,1.25,48
14,.00,NaN,NaN,NaN,NaN,filled & break circulation every 20 stands.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,"- 12,492' MD: 250 gpm, 1,797 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.5+ ppg / 10.5+ ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"12:00 0.25 3,598",NaN,8 1/2 D,NaN,PRO,Held,NaN,NaN,NaN,NaN,NaN,0.25,48
19,.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"12:15 2.00 3,600",NaN,8 1/2 D,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,2.00,48
21,.25,NaN,NaN,NaN,NaN,filled & break circulation every 20 stands.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,"- 12,492' MD: 250 gpm, 1,797 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,"- 14,290' MD, 250 gpm, 1,861 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.5+ ppg / 9.6+ - 10.5+ ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"14:15 1.50 3,601",NaN,8 1/2 DR,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,1.50,48
27,.75,NaN,NaN,NaN,NaN,filled & break circulation.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,"- 15,239' MD: 250 gpm, 1,992 psi. (check MWD t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.5 ppg / 9.7 ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,"- Confirmed MWD tool temp at 15,239' MD ( 287 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,"to (TOL 16,000' MD 300 F).",NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,"Decision made to wash down from 16,000' MD to ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,temperature on MWD tools.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"15:45 0.25 3,602",NaN,8 1/2 G,NaN,PRO,Continued to,NaN,NaN,NaN,NaN,NaN,0.25,48
37,.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"16:00 0.25 3,602",NaN,8 1/2 LG,NaN,PRO,Held Well,NaN,NaN,NaN,NaN,NaN,0.25,48
39,.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,"16:15 1.25 3,603",NaN,8 1/2 LG,NaN,PRO,M/U,NaN,NaN,NaN,NaN,NaN,1.25,48
41,.50,NaN,NaN,NaN,NaN,"16,365' MD, 250 gpm, 2,181 psi - 2,550 psi.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,Parameters.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,"- 16,370' MD, S/O: 298 k , 30 rpm, 8 k trq. (P...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,"- 16,370' MD, P/U: 352 k, S/O 305 k (Pumps Off)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,- MW in/out: 10.4 - 10.5 ppg / 9.7 - 10+ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,- MWD tool D/H Temp: 290 F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 4 from BAV-102- WO DDR-01-July-17.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,NaN,NaN,NaN,24.00,NaN,"5,096,832",No
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARR0,2023,TESTE,TESTE,TESTE,TESTE,TESTE

Table 5 from BAV-102- WO DDR-01-July-17.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,Curr. KB to Mud Time Log Hrs,NaN,NaN,Target Depth,Target Depth,Depth End (MD),End Depth,NaN,Duration
2,(days) (days),Water Depth (ft),(ft) Current RKB,NaN,Line (ft) (hr),Drill Hrs (hr),NaN,(MD) (ftKB),(TVD) (ftOTH),(ftKB),(TVD) (ftOTH),NaN,(days)
3,54 54,"1,281.00","202.00 202.00,",NaN,"1,483.00 24.00",NaN,NaN,"22,205","15,906.5","17,455",NaN,NaN,115.16
4,Job Time Log,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Start Cum Dur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unsch,NaN
6,Time Dur (hr) (hr),Hole/Csg Size,Well Phase,Phase,Activity,NaN,NaN,Com,NaN,NaN,NaN,Time (hr),Ref No.
7,"17:30 2.50 3,606",8 1/2 DR,PRO,NaN,Continued to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,.00,NaN,NaN,NaN,"250 gpm, 2500 psi. Commenced wash & ream from...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,"MD, 20 rpm, 7 k trq.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,- Run through TOL - slick. MW in/out: 10.4 - 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,"- TG: 2% while entering 7"" Liner. SPP graduall...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,"from 15,000' MD.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"20:00 3.50 3,609",8 1/2 LG,PRO,NaN,Circulated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,.50,NaN,NaN,NaN,"Pump rate: 350 gpm / SPP: 3,800 - 3,520 psi.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,TDS rotary: 20 -30 rpm / TRQ: 9-10 k.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,"Gas: 2.42 %. MW in/out: 10.5, 10.5+ / 10.6+, 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,Initial ECD: 12 ppg and Final ECD: 10.98 ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,"- Performed Table top choke drill with TP, Dri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,RSP and POA with Data and Mud engineers.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,- Observed discrepancy between Geolog and NOV'...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,psi difference).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,- Bottom Up at surface MW in/out: 10.5+ and 10...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,"- After 1.5 BU MW in: 10.5, 10.4+ / MW out: 10...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"23:30 0.50 3,610",8 1/2 G,PRO,NaN,Commenced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,.00,NaN,NaN,NaN,T Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,"FR: 300 gpm / SPP: 2,901 psi.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,WOB: 5-8 / TRQ: 11-12 Rotation: 80 rpm.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,MW in: 10.5 ppg & MW out: 10.5 ppg.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,- Recorded PUW: 362 k / SOW; 308 k / ROW: 340 k.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,"- After BPUTS at 17,314' MD, observed SPP from...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Offline Activity Time Logs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Start Date,Dur (hr),Activity,NaN,Inactive?,NaN,NaN,NaN,Com,NaN,NaN,NaN,NaN
36,Unscheduled Events,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Ref No. Unscheduled EvSetnatr tT Dypaete,NaN,Dur (Net) (hr),Unscheduled Major Category,Unscheduled Detail,NaN,NaN,Start Depth (MD) (ftOTH) End Depth (MD) (ftOTH),NaN,Estimated Cost (Cost),NaN,NaN,Exclude from NPT Calculation
38,48 NPT 5/16/2024 07:15,NaN,106.25,RREQ,TOP DRIVE,NaN,NaN,"16,300","16,300",NaN,NaN,NaN,N
39,Event Description,NaN,NaN,NaN,NaN,NaN,Accountable Party,NaN,NaN,Service Contractor,NaN,NaN,NaN
40,Continue waiting,NaN,NaN,NaN,NaN,NaN,Rig Contractor,NaN,NaN,TTTT,NaN,NaN,NaN
41,Job Supplies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Job Supply Type,Supply Item Des,NaN,Received,Returned,NaN,NaN,Consumed,Cum On Loc,NaN,Cum Consumed,NaN,NaN
43,Water,Non-potable Water,NaN,NaN,0.0,0.0,NaN,11.0,NaN,"4,168.0",NaN,NaN,"19,497.0"
44,Water,Potable Water,NaN,NaN,298.0,0.0,NaN,255.0,NaN,"6,277.0",NaN,NaN,"33,016.0"
45,Base Fluid,Non-aqueous,NaN,NaN,0.0,0.0,NaN,8.0,NaN,"1,070.0",NaN,NaN,"1,978.0"
46,Base Fluid,Diesel,NaN,NaN,0.0,0.0,NaN,71.0,NaN,"3,350.0",NaN,NaN,"13,713.0"
47,Cement,Class G,NaN,NaN,0.0,0.0,NaN,0.0,NaN,"-4,947.0",NaN,NaN,"9,894.0"
48,Cement,Blend,NaN,NaN,0.0,0.0,NaN,0.0,NaN,"3,556.0",NaN,NaN,"3,319.0"
49,Brine,KCl,NaN,NaN,0.0,0.0,NaN,0.0,NaN,"1,280.0",NaN,NaN,457.0
50,Cement,Neat,NaN,NaN,0.0,0.0,NaN,0.0,NaN,-825.0,NaN,NaN,"2,959.0"
51,"Drill String/BHA: BHA #<StringNo>, <Des>",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,String Components,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IADC Bit Dull Out,NaN,NaN,NaN
53,Size (in) Model,Serial Number,Depth In (ftOTH),NaN,Depth Out (ftOTH) Total Depth Drilled by Bit (...,NaN,NaN,Total Avg ROP (ft/hr),NaN,String Length (ft),String Wt (1000lbf),NaN,NaN
54,Drill String Drilling Parameter: <DepthStart> ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Start Depth (TVD) (ftOTH),End Depth (TVD) (ftOTH),Depth Start (MD) (ftOTH),NaN,Depth End (MD) (ftOTH),Interval Depth Drilled (ft),NaN,NaN,Drill Time w/connections (hr),NaN,Interval ROP (ft/hr),NaN,NaN
56,RPM (rpm) Motor RPM (rpm),NaN,Weight on Bit (1000lbf),NaN,PU Str Wt (1000lbf) SO Str Wt (1000lbf),NaN,NaN,Drilling Torque,Off Bottom Torque,NaN,ROP Instantaneous (ft/hr),NaN,NaN
57,Hydraulic Calculations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Mud Density (lb/gal) TFA (incl Noz) (in2),Flow Rate (gpm),SPP (psi),NaN,Bit Jet Velocity (ft/s) Bit Pressure Drop (psi),NaN,HSI (hp/in2),ECD End (lb/gal),NaN,Min Open Hole AV (ft/min),Max Open Hole AV (ft/min),NaN,NaN
59,Error,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 6 from BAV-102- WO DDR-01-July-17.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,NaN,NaN,NaN,24.00,NaN,"5,096,832",NaN
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARRO,2023,TESTE,TESTE,TESTE,TESTE,TESTE

Table 7 from BAV-102- WO DDR-01-July-17.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,Curr. KB to Mud Time Log Hrs,NaN,Target Depth,Target Depth,Depth End (MD) End Depth,NaN,NaN,Duration
2,(days) (days),Water Depth (ft),(ft),Current RKB,Line (ft) (hr) Drill Hrs (hr),NaN,(MD) (ftKB),(TVD) (ftOTH),(ftKB) (TVD) (ftOTH),NaN,NaN,(days)
3,54 54,"1,281.00","202.00 202.00,",NaN,"1,483.00 24.00",NaN,"22,205","15,906.5","17,455",NaN,NaN,115.16
4,Casing Strings (WSEA 5),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
73,AFE Number Total AFE Amount (Cost),NaN,Total AFE + Sup Amount (Cost)Cum Field Est To ...,NaN,Daily Field Est Total (Cost),NaN,Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?,NaN,NaN,NaN
74,"73,336,000",NaN,NaN,NaN,NaN,24.00,NaN,NaN,NaN,NaN,NaN,NaN
75,Well Name Wellbore,NaN,Job Category,NaN,Job Complexity Complex Job Assessment,NaN,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor,NaN,NaN,NaN
76,2023,NaN,TESTE,NaN,TESTE,NaN,TESTE,TESTE,TESTE,NaN,NaN,NaN
77,CARRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 8 from BAV-102- WO DDR-01-July-17.pdf:

,Days Since Days Since,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Lost Time Recordable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planned AFE
1,Incident Incident,NaN,Original RKB,NaN,NaN,Curr. KB to Mud Time Log Hrs,NaN,NaN,Target Depth Target Depth,Depth End (MD),NaN,End Depth,Duration
2,(days) (days),Water Depth (ft),(ft),Current RKB,NaN,Line (ft) (hr),Drill Hrs (hr),NaN,(MD) (ftKB) (TVD) (ftOTH),(ftKB),NaN,(TVD) (ftOTH),(days)
3,54 54,"1,281.00",202.00,"202.00,",NaN,"1,483.00 24.00",NaN,NaN,"22,205","15,906.5 17,455",NaN,NaN,115.16
4,Last 5 Surveys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,DLS Build,Turn,NaN,NaN,NaN,NaN,Use for,Definitiv
6,Date,TVD (ftOTH),MD (ftOTH),Incl (°),NaN,Azm (°) (°/100ft) (°/100ft),(°/100ft),NaN,VS (ft),NS (ft) EW (ft),NaN,Prop/Actual Calcs?,e?
7,Geologic Horizons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
9,Miocene,NaN,NaN,NaN,NaN,"3,616",NaN,NaN,NaN,NaN,NaN,"3,620",NaN
10,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
11,CN10,NaN,NaN,NaN,NaN,"4,520",NaN,NaN,NaN,NaN,NaN,"4,521",NaN
12,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
13,CN9,NaN,NaN,NaN,NaN,"4,826",NaN,NaN,NaN,NaN,NaN,"4,827",NaN
14,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
15,CN8,NaN,NaN,NaN,NaN,"5,935",NaN,NaN,NaN,NaN,NaN,"5,938",NaN
16,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
17,CN6,NaN,NaN,NaN,NaN,"6,479",NaN,NaN,NaN,NaN,NaN,"6,474",NaN
18,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
19,CN3,NaN,NaN,NaN,NaN,"11,568",NaN,NaN,NaN,NaN,NaN,"11,505",NaN
20,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
21,PTS 0,NaN,NaN,NaN,NaN,"17,709",NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Formation Name,NaN,NaN,NaN,NaN,Prognosed Top MD (ftOTH),Prognosed Bottom MD (ftOTH),NaN,NaN,Drilling Bottom MD (ftOTH),NaN,Drilling Top MD (ftOTH),NaN
23,PTS 5,NaN,NaN,NaN,NaN,"20,085",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Tubing Strings (run/pulled this Job),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,String Max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Nominal OD,NaN,Top Depth,NaN,Set Depth,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Run Date Pull Date,(in),Drift Min (in),(MD) (ftOTH),NaN,(MD) (ftOTH) Top Thread Wt (lb/ft),NaN,Grade,Des,NaN,NaN,Com,NaN
28,Other Strings/BHA: (still in hole),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,String Max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Nominal OD,NaN,Top Depth,NaN,Set Depth,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Run Date Pull Date,(in),Drift Min (in),(MD) (ftOTH),NaN,(ftOTH) Top Thread Wt (lb/ft),NaN,Grade,Tubing String,NaN,NaN,Com,NaN
32,Other in Hole (still in hole),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Run Date Pull Date,Fish Neck OD (in),NaN,Drift (in),NaN,Top (ftOTH) String,NaN,Des,NaN,Com,NaN,NaN,NaN
34,Perforations (this Job),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,Dens Fluis,P Over/Under Shot Dens Gun Left,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Date,Top (ftOTH),Btm (ftOTH),NaN,(lb/gal),(psi) (shots/ft) In Hole?,NaN,NaN,NaN,Com,NaN,NaN,NaN

Table 9 from BAV-102- WO DDR-01-July-17.pdf:

,Job Information,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,AFE Number,Total AFE Amount (Cost),Total AFE + Sup Amount (Cost)Cum Field Est To ...,Daily Field Est Total (Cost),Daily Mud Field Est (Cost),Cum Mud Cost to Date (Cost),Recordable Incident?
1,NaN,"73,336,000","103,571,861 91,083,426","362,306 24.00",NaN,"5,096,832",No
2,Well Name,Wellbore,Job Category Job Complexity,Complex Job Assessment,Surface ChevNo,Rig/Unit # / Name,Rig/Unit Contractor
3,CARRO,2023,TESTE,TESTE,TESTE,TESTE,TESTE